export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const REMOVE_CONTACT_SUCCESS = "REMOVE_CONTACT_SUCCESS";
